# Script for plotting any of the .csv files generated by LoggerPro
# Written by Blaire Ness

import csv
from matplotlib import pyplot as plt
import numpy as np
import math

# Read in file
data = input("Enter name of file to be plotted:")

time, voltage = np.genfromtxt(data, delimiter=",", unpack=True)

# Change voltage values to amplitude values

max_voltage = np.amax(voltage)

amplitude = []

def volt_to_amp(x):
    return (max_voltage-x)/(max_voltage)

for n in voltage:
    amplitude.append(volt_to_amp(n))

plt.plot(time, amplitude)
plt.xlabel("Degrees")
plt.ylabel("Flux")
#plt.show()

pngname = input("Enter name of file to be saved: ")
plt.savefig("%s.png" % pngname)
print("File saved to %s.png" % pngname)
